##################################################################################################
# Ingress Routing
##################################################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
         serviceName: hello-app
         servicePort: 80
      - path: /first
        backend:
          serviceName: hello-app
          servicePort: 80 
      - path: /second
        backend:
          serviceName: hello-app
          servicePort: 80 
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: 'true'  
  name: hello-app
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: hello-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        #image: wizplaycluster.icp:8500/default/hello-container:latest 
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  type: ClusterIP 
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: hello-app
